version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.8
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: flake8 -v --statistics --count
      - run: mypy aimachine --ignore-missing-imports
      - run: pylint aimachine
      - run: pytest -v